#! /bin/sh

case "$1" in
    start|restart|force-reload)
    # IO2 = gpio13

	if [ ! -d /sys/class/gpio/gpio13 ] ; then
	    echo -n "13" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio13/direction
	chgrp gpio /sys/class/gpio/gpio13/value
	chmod g+rw /sys/class/gpio/gpio13/value

  if [ ! -d /sys/class/gpio/gpio34 ] ; then
	    echo -n "34" > /sys/class/gpio/export
	fi
  echo -n "in" > /sys/class/gpio/gpio34/direction
	echo -n "1" > /sys/class/gpio/gpio34/value

  # 77 não tenho certeza se out ou in
  if [ ! -d /sys/class/gpio/gpio77 ] ; then
      echo -n "77" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio77/direction
  echo -n "0" > /sys/class/gpio/gpio77/value

	;;
    stop)
  echo -n "out" > /sys/class/gpio/gpio13/direction
  echo -n "13" > /sys/class/gpio/unexport
  echo -n "34" > /sys/class/gpio/unexport
	echo -n "77" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
