#! /bin/sh

case "$1" in
    start|restart|force-reload)
    # IO6 = gpio1

	if [ ! -d /sys/class/gpio/gpio1 ] ; then
	    echo -n "1" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio1/direction
	chgrp gpio /sys/class/gpio/gpio1/value
	chmod g+rw /sys/class/gpio/gpio1/value

  if [ ! -d /sys/class/gpio/gpio20 ] ; then
	    echo -n "20" > /sys/class/gpio/export
	fi
  echo -n "in" > /sys/class/gpio/gpio20/direction
	echo -n "1" > /sys/class/gpio/gpio20/value

  # 68 não tenho certeza se out ou in
  if [ ! -d /sys/class/gpio/gpio68 ] ; then
      echo -n "68" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio68/direction
  echo -n "0" > /sys/class/gpio/gpio68/value

	;;
    stop)
  echo -n "out" > /sys/class/gpio/gpio1/direction
  echo -n "1" > /sys/class/gpio/unexport
  echo -n "20" > /sys/class/gpio/unexport
	echo -n "68" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
