#! /bin/sh

case "$1" in
    start|restart|force-reload)
    # IO8 = gpio40

	if [ ! -d /sys/class/gpio/gpio40 ] ; then
	    echo -n "40" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio40/direction
	chgrp gpio /sys/class/gpio/gpio40/value
	chmod g+rw /sys/class/gpio/gpio40/value

  ;;
    stop)
  echo -n "out" > /sys/class/gpio/gpio40/direction
  echo -n "40" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
