#! /bin/sh

case "$1" in
    start|restart|force-reload)
    # IO9 = gpio4

	if [ ! -d /sys/class/gpio/gpio4 ] ; then
	    echo -n "4" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio4/direction
	chgrp gpio /sys/class/gpio/gpio4/value
	chmod g+rw /sys/class/gpio/gpio4/value

  if [ ! -d /sys/class/gpio/gpio22 ] ; then
	    echo -n "22" > /sys/class/gpio/export
	fi
  echo -n "in" > /sys/class/gpio/gpio22/direction
	echo -n "1" > /sys/class/gpio/gpio22/value

  # 70 não tenho certeza se out ou in
  if [ ! -d /sys/class/gpio/gpio70 ] ; then
      echo -n "70" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio70/direction
  echo -n "0" > /sys/class/gpio/gpio70/value

	;;
    stop)
  echo -n "out" > /sys/class/gpio/gpio4/direction
  echo -n "4" > /sys/class/gpio/unexport
  echo -n "22" > /sys/class/gpio/unexport
	echo -n "70" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
