#! /bin/sh

case "$1" in
    start|restart|force-reload)
    # IO12 = gpio15

	if [ ! -d /sys/class/gpio/gpio15 ] ; then
	    echo -n "15" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio15/direction
	chgrp gpio /sys/class/gpio/gpio15/value
	chmod g+rw /sys/class/gpio/gpio15/value

  if [ ! -d /sys/class/gpio/gpio24 ] ; then
	    echo -n "42" > /sys/class/gpio/export
	fi
  echo -n "out" > /sys/class/gpio/gpio24/direction
	echo -n "0" > /sys/class/gpio/gpio24/value
  ;;
    stop)
  echo -n "in" > /sys/class/gpio/gpio15/direction
  echo -n "15" > /sys/class/gpio/unexport
	echo -n "42" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
