#! /bin/sh

### BEGIN INIT INFO
# Provides:         
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO and PWM.
# Description:       Configures GPIO and PWM.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
        # IO5 = pwm3
	if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
	    echo -n "3" > /sys/class/pwm/pwmchip0/export
	fi
	chgrp trab /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
	chgrp trab /sys/class/pwm/pwmchip0/pwm3/duty_cycle
	chmod g+w /sys/class/pwm/pwmchip0/pwm3/duty_cycle
	chgrp trab /sys/class/pwm/pwmchip0/pwm3/enable
	chmod g+w /sys/class/pwm/pwmchip0/pwm3/enable
        
        # gpio18 = 0 = out
	if [ ! -d /sys/class/gpio/gpio18 ] ; then
	    echo -n "18" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio18/direction
	echo -n "0" > /sys/class/gpio/gpio18/value

        # gpio19 = in = no pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio19 ] ; then
	    echo -n "19" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio19/direction
        
        # gpio66 = 0
	if [ ! -d /sys/class/gpio/gpio66 ] ; then
	    echo -n "66" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio66/value
        
        # gpio64 = 1 */
	#if [ ! -d /sys/class/gpio/gpio64 ] ; then
	#    echo -n "64" > /sys/class/gpio/export
	#fi
	#echo -n "1" > /sys/class/gpio/gpio64/value
    	;;
    stop)
    	echo -n "0" > /sys/class/pwm/pwmchip0/pwm3/enable
    	echo -n "66" > /sys/class/gpio/unexport
        #echo -n "64" > /sys/class/gpio/unexport
	echo -n "19" > /sys/class/gpio/unexport
	echo -n "1" > /sys/class/gpio/gpio18/value
	echo -n "18" > /sys/class/gpio/unexport
	echo -n "1" > /sys/class/pwm/pwmchip0/unexport
	;;
    status)
    	echo -n Period:
    	cat /sys/class/pwm/pwmchip0/device/pwm_period
    	echo -n Duty Cicle:
    	cat /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    	echo -n Enable:
    	cat /sys/class/pwm/pwmchip0/pwm3/enable
	;;
    *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
