#! /bin/sh

case "$1" in
    start|restart|force-reload)
    # IO13 = gpio7

	if [ ! -d /sys/class/gpio/gpio7 ] ; then
	    echo -n "7" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio7/direction
	chgrp gpio /sys/class/gpio/gpio7/value
	chmod g+rw /sys/class/gpio/gpio7/value

  if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
  echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "0" > /sys/class/gpio/gpio30/value

  if [ ! -d /sys/class/gpio/gpio46 ] ; then
      echo -n "46" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio46/direction
  echo -n "0" > /sys/class/gpio/gpio46/value
  ;;
    stop)
  echo -n "in" > /sys/class/gpio/gpio7/direction
  echo -n "7" > /sys/class/gpio/unexport
  echo -n "30" > /sys/class/gpio/unexport
	echo -n "46" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
