#! /bin/sh

case "$1" in
    start|restart|force-reload)
  # IO15 = gpio50
	if [ ! -d /sys/class/gpio/gpio50 ] ; then
	    echo -n "50" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio50/direction
	chgrp gpio /sys/class/gpio/gpio50/value
	chmod g+rw /sys/class/gpio/gpio50/value
	;;
    stop)
    	echo -n "out" > /sys/class/gpio/gpio50/direction
    	echo -n "50" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac
